INCLUDE "emu8086.inc"

TAMANHO EQU 32

org 100h
DEFINE_GET_STRING   
DEFINE_PRINT_STRING


MOV SI, OFFSET MENS1
CALL PRINT_STRING      

MOV DI, OFFSET SUBSTRING
MOV DX, TAMANHO + 1
CALL GET_STRING 
CALL PULA_LINHA

MOV SI, OFFSET MENS2
CALL PRINT_STRING

MOV DI, OFFSET STRING
MOV DX, TAMANHO + 1
CALL GET_STRING 

CALL PULA_LINHA
                     
MOV SI, OFFSET SUBSTRING
MOV DI, OFFSET STRING                     
CALL PROCURAR_PALAVRA

MOV AH, 4CH
MOV AL, 0
INT 21H

PULA_LINHA:                       
PUSHF
PUSH AX
PUSH DX
MOV AH,2
MOV DL,13          
INT 21H
MOV AH,2
MOV DL,10
INT 21H
POP DX          
POP AX
POPF
ret

PROCURAR_PALAVRA:
PUSHF
PUSH DI
PUSH DX

INICIAR:
PUSH SI

COMPARAR_LETRA:
MOV DH, [SI]
MOV DL, [DI]

CMP DH, 0
JZ IMPRIMIR_ACHOU
CMP DL, 0
JZ IMPRIMIR_NAO_ACHOU

CMP DH, DL
JE PROXIMA_LETRA
POP SI
INC DI
JMP INICIAR

PROXIMA_LETRA:
INC SI
INC DI
JMP COMPARAR_LETRA
       
IMPRIMIR_ACHOU:
MOV SI, OFFSET MENSSUB
CALL PRINT_STRING
MOV SI, OFFSET SUBSTRING
CALL PRINT_STRING 
MOV SI, OFFSET MENSRET
CALL PRINT_STRING
MOV SI, OFFSET STRING
CALL PRINT_STRING       
JMP FIM_PROCURAR_PALAVRA
 

IMPRIMIR_NAO_ACHOU:
MOV SI, OFFSET MENSSUB
CALL PRINT_STRING
MOV SI, OFFSET SUBSTRING
CALL PRINT_STRING
MOV SI, OFFSET MENSNAO
CALL PRINT_STRING 
MOV SI, OFFSET MENSRET
CALL PRINT_STRING
MOV SI, OFFSET STRING
CALL PRINT_STRING
JMP FIM_PROCURAR_PALAVRA

FIM_PROCURAR_PALAVRA:
POP SI
POP DX
POP DI
POPF
ret 

MENS1 DB "DIGITE SUBSTRING ",0
MENS2 DB "DIGITE STRING ",0
MENSSUB DB "A SUBSTRING ",0
MENSNAO DB " NAO",0
MENSRET DB " ESTA NA STRING ",0
SUBSTRING DB TAMANHO DUP(" "),0
STRING DB TAMANHO DUP(" "),0

